/**:
  ros__parameters:

    # Topics
    pointCloudTopic: "/velodyne_points"
    imuTopic: "/handsfree/imu"
    odomTopic: "odometry/imu"
    gpsTopic: "odometry/gpsz"

    # Frames
    lidarFrame: "base_link"
    baselinkFrame: "base_link"
    odometryFrame: "odom"
    mapFrame: "map"

    # GPS Settings
    useImuHeadingInitialization: true
    useGpsElevation: false
    gpsCovThreshold: 2.0
    poseCovThreshold: 25.0

    # Export settings
    savePCD: false
    savePCDDirectory: "/Downloads/LOAM/"

    # Sensor Settings
    sensor: velodyne                         # lidar sensor type
    N_SCAN: 32                               # VLP-32C has 32 channels
    Horizon_SCAN: 1800                       # Standard Velodyne resolution
    downsampleRate: 1                        # 1 = Use all points (10Hz is manageable)
    lidarMinRange: 1.0                       # Filter body reflections
    lidarMaxRange: 1000.0

    # IMU Settings
    imuAccNoise: 3.7686306102624571e-02
    imuGyrNoise: 2.3417543020438883e-03
    imuAccBiasN: 1.1416642385952368e-03
    imuGyrBiasN: 1.4428407712885209e-05
    imuGravity: 9.80511
    imuRPYWeight: 0.01

    # Extrinsics
    extrinsicTrans: [0.27255, -0.00053, 0.17954]
 # Rotation: Identity Matrix (No rotation - typically correct for M2DGR)
    extrinsicRot: [1.0, 0.0, 0.0,
                   0.0, 1.0, 0.0,
                   0.0, 0.0, 1.0]
                   
    # RPY: Zero
    extrinsicRPY: [1.0, 0.0, 0.0,
                   0.0, 1.0, 0.0,
                   0.0, 0.0, 1.0]
    # Feature thresholds
    edgeThreshold: 1.0
    surfThreshold: 0.1
    edgeFeatureMinValidNum: 10
    surfFeatureMinValidNum: 100

    # Voxel filters
    odometrySurfLeafSize: 0.4
    mappingCornerLeafSize: 0.2
    mappingSurfLeafSize: 0.4

    # Motion constraints
    z_tollerance: 1000.0
    rotation_tollerance: 1000.0

    # CPU
    numberOfCores: 4
    mappingProcessInterval: 0.15

    # Surrounding map
    surroundingkeyframeAddingDistThreshold: 1.0
    surroundingkeyframeAddingAngleThreshold: 0.2
    surroundingKeyframeDensity: 2.0
    surroundingKeyframeSearchRadius: 50.0

    # Loop closure
    loopClosureEnableFlag: true
    loopClosureFrequency: 1.0
    surroundingKeyframeSize: 50
    historyKeyframeSearchRadius: 15.0
    historyKeyframeSearchTimeDiff: 30.0
    historyKeyframeSearchNum: 25
    historyKeyframeFitnessScore: 0.3

    # Visualization
    globalMapVisualizationSearchRadius: 1000.0
    globalMapVisualizationPoseDensity: 10.0
    globalMapVisualizationLeafSize: 1.0
